# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@alcalzone/ansi-tokenize@0.1.3" = fetchurl {
    url = "https://registry.npmjs.org/@alcalzone/ansi-tokenize/-/ansi-tokenize-0.1.3.tgz";
    hash = "sha512-3yWxPTq3UQ/FY9p1ErPxIyfT64elWaMvM9lIHnaqpyft63tkxodF5aUElYHrdisWve5cETkh1+KBw1yJuW0aRw==";
  };
  "@biomejs/biome@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/biome/-/biome-2.1.2.tgz";
    hash = "sha512-yq8ZZuKuBVDgAS76LWCfFKHSYIAgqkxVB3mGVVpOe2vSkUTs7xG46zXZeNPRNVjiJuw0SZ3+J2rXiYx0RUpfGg==";
  };
  "@biomejs/cli-darwin-arm64@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-darwin-arm64/-/cli-darwin-arm64-2.1.2.tgz";
    hash = "sha512-leFAks64PEIjc7MY/cLjE8u5OcfBKkcDB0szxsWUB4aDfemBep1WVKt0qrEyqZBOW8LPHzrFMyDl3FhuuA0E7g==";
  };
  "@biomejs/cli-darwin-x64@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-darwin-x64/-/cli-darwin-x64-2.1.2.tgz";
    hash = "sha512-Nmmv7wRX5Nj7lGmz0FjnWdflJg4zii8Ivruas6PBKzw5SJX/q+Zh2RfnO+bBnuKLXpj8kiI2x2X12otpH6a32A==";
  };
  "@biomejs/cli-linux-arm64-musl@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-arm64-musl/-/cli-linux-arm64-musl-2.1.2.tgz";
    hash = "sha512-qgHvafhjH7Oca114FdOScmIKf1DlXT1LqbOrrbR30kQDLFPEOpBG0uzx6MhmsrmhGiCFCr2obDamu+czk+X0HQ==";
  };
  "@biomejs/cli-linux-arm64@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-arm64/-/cli-linux-arm64-2.1.2.tgz";
    hash = "sha512-NWNy2Diocav61HZiv2enTQykbPP/KrA/baS7JsLSojC7Xxh2nl9IczuvE5UID7+ksRy2e7yH7klm/WkA72G1dw==";
  };
  "@biomejs/cli-linux-x64-musl@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-x64-musl/-/cli-linux-x64-musl-2.1.2.tgz";
    hash = "sha512-xlB3mU14ZUa3wzLtXfmk2IMOGL+S0aHFhSix/nssWS/2XlD27q+S6f0dlQ8WOCbYoXcuz8BCM7rCn2lxdTrlQA==";
  };
  "@biomejs/cli-linux-x64@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-x64/-/cli-linux-x64-2.1.2.tgz";
    hash = "sha512-Km/UYeVowygTjpX6sGBzlizjakLoMQkxWbruVZSNE6osuSI63i4uCeIL+6q2AJlD3dxoiBJX70dn1enjQnQqwA==";
  };
  "@biomejs/cli-win32-arm64@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-win32-arm64/-/cli-win32-arm64-2.1.2.tgz";
    hash = "sha512-G8KWZli5ASOXA3yUQgx+M4pZRv3ND16h77UsdunUL17uYpcL/UC7RkWTdkfvMQvogVsAuz5JUcBDjgZHXxlKoA==";
  };
  "@biomejs/cli-win32-x64@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-win32-x64/-/cli-win32-x64-2.1.2.tgz";
    hash = "sha512-9zajnk59PMpjBkty3bK2IrjUsUHvqe9HWwyAWQBjGLE7MIBjbX2vwv1XPEhmO2RRuGoTkVx3WCanHrjAytICLA==";
  };
  "@ccflare/agents" = copyPathToStore ./packages/agents;
  "@ccflare/cli-commands" = copyPathToStore ./packages/cli-commands;
  "@ccflare/config" = copyPathToStore ./packages/config;
  "@ccflare/core" = copyPathToStore ./packages/core;
  "@ccflare/core-di" = copyPathToStore ./packages/core-di;
  "@ccflare/dashboard-web" = copyPathToStore ./packages/dashboard-web;
  "@ccflare/database" = copyPathToStore ./packages/database;
  "@ccflare/errors" = copyPathToStore ./packages/errors;
  "@ccflare/http-api" = copyPathToStore ./packages/http-api;
  "@ccflare/http-common" = copyPathToStore ./packages/http-common;
  "@ccflare/lander" = copyPathToStore ./apps/lander;
  "@ccflare/load-balancer" = copyPathToStore ./packages/load-balancer;
  "@ccflare/logger" = copyPathToStore ./packages/logger;
  "@ccflare/oauth-flow" = copyPathToStore ./packages/oauth-flow;
  "@ccflare/providers" = copyPathToStore ./packages/providers;
  "@ccflare/proxy" = copyPathToStore ./packages/proxy;
  "@ccflare/server" = copyPathToStore ./apps/server;
  "@ccflare/tui-core" = copyPathToStore ./packages/tui-core;
  "@ccflare/types" = copyPathToStore ./packages/types;
  "@ccflare/ui-common" = copyPathToStore ./packages/ui-common;
  "@ccflare/ui-constants" = copyPathToStore ./packages/ui-constants;
  "@dqbd/tiktoken@1.0.21" = fetchurl {
    url = "https://registry.npmjs.org/@dqbd/tiktoken/-/tiktoken-1.0.21.tgz";
    hash = "sha512-grBxRSY9+/iBM205EWjbMm5ySeXQrhJyXWMP38VJd+pO2DRGraDAbi4n8J8T9M4XY1M/FHgonMcmu3J+KjcX0Q==";
  };
  "@floating-ui/core@1.7.2" = fetchurl {
    url = "https://registry.npmjs.org/@floating-ui/core/-/core-1.7.2.tgz";
    hash = "sha512-wNB5ooIKHQc+Kui96jE/n69rHFWAVoxn5CAzL1Xdd8FG03cgY3MLO+GF9U3W737fYDSgPWA6MReKhBQBop6Pcw==";
  };
  "@floating-ui/dom@1.7.2" = fetchurl {
    url = "https://registry.npmjs.org/@floating-ui/dom/-/dom-1.7.2.tgz";
    hash = "sha512-7cfaOQuCS27HD7DX+6ib2OrnW+b4ZBwDNnCcT0uTyidcmyWb03FnQqJybDBoCnpdxwBSfA94UAYlRCt7mV+TbA==";
  };
  "@floating-ui/react-dom@2.1.4" = fetchurl {
    url = "https://registry.npmjs.org/@floating-ui/react-dom/-/react-dom-2.1.4.tgz";
    hash = "sha512-JbbpPhp38UmXDDAu60RJmbeme37Jbgsm7NrHGgzYYFKmblzRUh6Pa641dII6LsjwF4XlScDrde2UAzDo/b9KPw==";
  };
  "@floating-ui/utils@0.2.10" = fetchurl {
    url = "https://registry.npmjs.org/@floating-ui/utils/-/utils-0.2.10.tgz";
    hash = "sha512-aGTxbpbg8/b5JfU1HXSrbH3wXZuLPJcNEcZQFMxLs3oSzgtVu6nFPkbbGGUvBcUjKV2YyB9Wxxabo+HEH9tcRQ==";
  };
  "@radix-ui/number@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/number/-/number-1.1.1.tgz";
    hash = "sha512-MkKCwxlXTgz6CFoJx3pCwn07GKp36+aZyu/u2Ln2VrA5DcdyCZkASEDBTd8x5whTQQL5CiYf4prXKLcgQdv29g==";
  };
  "@radix-ui/primitive@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/primitive/-/primitive-1.1.2.tgz";
    hash = "sha512-XnbHrrprsNqZKQhStrSwgRUQzoCI1glLzdw79xiZPoofhGICeZRSQ3dIxAKH1gb3OHfNf4d6f+vAv3kil2eggA==";
  };
  "@radix-ui/react-arrow@1.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-arrow/-/react-arrow-1.1.7.tgz";
    hash = "sha512-F+M1tLhO+mlQaOWspE8Wstg+z6PwxwRd8oQ8IXceWz92kfAmalTRf0EjrouQeo7QssEPfCn05B4Ihs1K9WQ/7w==";
  };
  "@radix-ui/react-collection@1.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-collection/-/react-collection-1.1.7.tgz";
    hash = "sha512-Fh9rGN0MoI4ZFUNyfFVNU4y9LUz93u9/0K+yLgA2bwRojxM8JU1DyvvMBabnZPBgMWREAJvU2jjVzq+LrFUglw==";
  };
  "@radix-ui/react-compose-refs@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-compose-refs/-/react-compose-refs-1.1.2.tgz";
    hash = "sha512-z4eqJvfiNnFMHIIvXP3CY57y2WJs5g2v3X0zm9mEJkrkNv4rDxu+sg9Jh8EkXyeqBkB7SOcboo9dMVqhyrACIg==";
  };
  "@radix-ui/react-context@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-context/-/react-context-1.1.2.tgz";
    hash = "sha512-jCi/QKUM2r1Ju5a3J64TH2A5SpKAgh0LpknyqdQ4m6DCV0xJ2HG1xARRwNGPQfi1SLdLWZ1OJz6F4OMBBNiGJA==";
  };
  "@radix-ui/react-dialog@1.1.14" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-dialog/-/react-dialog-1.1.14.tgz";
    hash = "sha512-+CpweKjqpzTmwRwcYECQcNYbI8V9VSQt0SNFKeEBLgfucbsLssU6Ppq7wUdNXEGb573bMjFhVjKVll8rmV6zMw==";
  };
  "@radix-ui/react-direction@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-direction/-/react-direction-1.1.1.tgz";
    hash = "sha512-1UEWRX6jnOA2y4H5WczZ44gOOjTEmlqv1uNW4GAJEO5+bauCBhv8snY65Iw5/VOS/ghKN9gr2KjnLKxrsvoMVw==";
  };
  "@radix-ui/react-dismissable-layer@1.1.10" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-dismissable-layer/-/react-dismissable-layer-1.1.10.tgz";
    hash = "sha512-IM1zzRV4W3HtVgftdQiiOmA0AdJlCtMLe00FXaHwgt3rAnNsIyDqshvkIW3hj/iu5hu8ERP7KIYki6NkqDxAwQ==";
  };
  "@radix-ui/react-dropdown-menu@2.1.15" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-dropdown-menu/-/react-dropdown-menu-2.1.15.tgz";
    hash = "sha512-mIBnOjgwo9AH3FyKaSWoSu/dYj6VdhJ7frEPiGTeXCdUFHjl9h3mFh2wwhEtINOmYXWhdpf1rY2minFsmaNgVQ==";
  };
  "@radix-ui/react-focus-guards@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-focus-guards/-/react-focus-guards-1.1.2.tgz";
    hash = "sha512-fyjAACV62oPV925xFCrH8DR5xWhg9KYtJT4s3u54jxp+L/hbpTY2kIeEFFbFe+a/HCE94zGQMZLIpVTPVZDhaA==";
  };
  "@radix-ui/react-focus-scope@1.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-focus-scope/-/react-focus-scope-1.1.7.tgz";
    hash = "sha512-t2ODlkXBQyn7jkl6TNaw/MtVEVvIGelJDCG41Okq/KwUsJBwQ4XVZsHAVUkK4mBv3ewiAS3PGuUWuY2BoK4ZUw==";
  };
  "@radix-ui/react-id@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-id/-/react-id-1.1.1.tgz";
    hash = "sha512-kGkGegYIdQsOb4XjsfM97rXsiHaBwco+hFI66oO4s9LU+PLAC5oJ7khdOVFxkhsmlbpUqDAvXw11CluXP+jkHg==";
  };
  "@radix-ui/react-label@2.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-label/-/react-label-2.1.7.tgz";
    hash = "sha512-YT1GqPSL8kJn20djelMX7/cTRp/Y9w5IZHvfxQTVHrOqa2yMl7i/UfMqKRU5V7mEyKTrUVgJXhNQPVCG8PBLoQ==";
  };
  "@radix-ui/react-menu@2.1.15" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-menu/-/react-menu-2.1.15.tgz";
    hash = "sha512-tVlmA3Vb9n8SZSd+YSbuFR66l87Wiy4du+YE+0hzKQEANA+7cWKH1WgqcEX4pXqxUFQKrWQGHdvEfw00TjFiew==";
  };
  "@radix-ui/react-popover@1.1.14" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-popover/-/react-popover-1.1.14.tgz";
    hash = "sha512-ODz16+1iIbGUfFEfKx2HTPKizg2MN39uIOV8MXeHnmdd3i/N9Wt7vU46wbHsqA0xoaQyXVcs0KIlBdOA2Y95bw==";
  };
  "@radix-ui/react-popper@1.2.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-popper/-/react-popper-1.2.7.tgz";
    hash = "sha512-IUFAccz1JyKcf/RjB552PlWwxjeCJB8/4KxT7EhBHOJM+mN7LdW+B3kacJXILm32xawcMMjb2i0cIZpo+f9kiQ==";
  };
  "@radix-ui/react-portal@1.1.9" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-portal/-/react-portal-1.1.9.tgz";
    hash = "sha512-bpIxvq03if6UNwXZ+HTK71JLh4APvnXntDc6XOX8UVq4XQOVl7lwok0AvIl+b8zgCw3fSaVTZMpAPPagXbKmHQ==";
  };
  "@radix-ui/react-presence@1.1.4" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-presence/-/react-presence-1.1.4.tgz";
    hash = "sha512-ueDqRbdc4/bkaQT3GIpLQssRlFgWaL/U2z/S31qRwwLWoxHLgry3SIfCwhxeQNbirEUXFa+lq3RL3oBYXtcmIA==";
  };
  "@radix-ui/react-primitive@2.1.3" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-primitive/-/react-primitive-2.1.3.tgz";
    hash = "sha512-m9gTwRkhy2lvCPe6QJp4d3G1TYEUHn/FzJUtq9MjH46an1wJU+GdoGC5VLof8RX8Ft/DlpshApkhswDLZzHIcQ==";
  };
  "@radix-ui/react-progress@1.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-progress/-/react-progress-1.1.7.tgz";
    hash = "sha512-vPdg/tF6YC/ynuBIJlk1mm7Le0VgW6ub6J2UWnTQ7/D23KXcPI1qy+0vBkgKgd38RCMJavBXpB83HPNFMTb0Fg==";
  };
  "@radix-ui/react-roving-focus@1.1.10" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-roving-focus/-/react-roving-focus-1.1.10.tgz";
    hash = "sha512-dT9aOXUen9JSsxnMPv/0VqySQf5eDQ6LCk5Sw28kamz8wSOW2bJdlX2Bg5VUIIcV+6XlHpWTIuTPCf/UNIyq8Q==";
  };
  "@radix-ui/react-select@2.2.5" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-select/-/react-select-2.2.5.tgz";
    hash = "sha512-HnMTdXEVuuyzx63ME0ut4+sEMYW6oouHWNGUZc7ddvUWIcfCva/AMoqEW/3wnEllriMWBa0RHspCYnfCWJQYmA==";
  };
  "@radix-ui/react-separator@1.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-separator/-/react-separator-1.1.7.tgz";
    hash = "sha512-0HEb8R9E8A+jZjvmFCy/J4xhbXy3TV+9XSnGJ3KvTtjlIUy/YQ/p6UYZvi7YbeoeXdyU9+Y3scizK6hkY37baA==";
  };
  "@radix-ui/react-slot@1.2.3" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-slot/-/react-slot-1.2.3.tgz";
    hash = "sha512-aeNmHnBxbi2St0au6VBVC7JXFlhLlOnvIIlePNniyUNAClzmtAUEY8/pBiK3iHjufOlwA+c20/8jngo7xcrg8A==";
  };
  "@radix-ui/react-switch@1.2.5" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-switch/-/react-switch-1.2.5.tgz";
    hash = "sha512-5ijLkak6ZMylXsaImpZ8u4Rlf5grRmoc0p0QeX9VJtlrM4f5m3nCTX8tWga/zOA8PZYIR/t0p2Mnvd7InrJ6yQ==";
  };
  "@radix-ui/react-tabs@1.1.12" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-tabs/-/react-tabs-1.1.12.tgz";
    hash = "sha512-GTVAlRVrQrSw3cEARM0nAx73ixrWDPNZAruETn3oHCNP6SbZ/hNxdxp+u7VkIEv3/sFoLq1PfcHrl7Pnp0CDpw==";
  };
  "@radix-ui/react-tooltip@1.2.7" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-tooltip/-/react-tooltip-1.2.7.tgz";
    hash = "sha512-Ap+fNYwKTYJ9pzqW+Xe2HtMRbQ/EeWkj2qykZ6SuEV4iS/o1bZI5ssJbk4D2r8XuDuOBVz/tIx2JObtuqU+5Zw==";
  };
  "@radix-ui/react-use-callback-ref@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-callback-ref/-/react-use-callback-ref-1.1.1.tgz";
    hash = "sha512-FkBMwD+qbGQeMu1cOHnuGB6x4yzPjho8ap5WtbEJ26umhgqVXbhekKUQO+hZEL1vU92a3wHwdp0HAcqAUF5iDg==";
  };
  "@radix-ui/react-use-controllable-state@1.2.2" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-controllable-state/-/react-use-controllable-state-1.2.2.tgz";
    hash = "sha512-BjasUjixPFdS+NKkypcyyN5Pmg83Olst0+c6vGov0diwTEo6mgdqVR6hxcEgFuh4QrAs7Rc+9KuGJ9TVCj0Zzg==";
  };
  "@radix-ui/react-use-effect-event@0.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-effect-event/-/react-use-effect-event-0.0.2.tgz";
    hash = "sha512-Qp8WbZOBe+blgpuUT+lw2xheLP8q0oatc9UpmiemEICxGvFLYmHm9QowVZGHtJlGbS6A6yJ3iViad/2cVjnOiA==";
  };
  "@radix-ui/react-use-escape-keydown@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-escape-keydown/-/react-use-escape-keydown-1.1.1.tgz";
    hash = "sha512-Il0+boE7w/XebUHyBjroE+DbByORGR9KKmITzbR7MyQ4akpORYP/ZmbhAr0DG7RmmBqoOnZdy2QlvajJ2QA59g==";
  };
  "@radix-ui/react-use-layout-effect@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-layout-effect/-/react-use-layout-effect-1.1.1.tgz";
    hash = "sha512-RbJRS4UWQFkzHTTwVymMTUv8EqYhOp8dOOviLj2ugtTiXRaRQS7GLGxZTLL1jWhMeoSCf5zmcZkqTl9IiYfXcQ==";
  };
  "@radix-ui/react-use-previous@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-previous/-/react-use-previous-1.1.1.tgz";
    hash = "sha512-2dHfToCj/pzca2Ck724OZ5L0EVrr3eHRNsG/b3xQJLA2hZpVCS99bLAX+hm1IHXDEnzU6by5z/5MIY794/a8NQ==";
  };
  "@radix-ui/react-use-rect@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-rect/-/react-use-rect-1.1.1.tgz";
    hash = "sha512-QTYuDesS0VtuHNNvMh+CjlKJ4LJickCMUAqjlE3+j8w+RlRpwyX3apEQKGFzbZGdo7XNG1tXa+bQqIE7HIXT2w==";
  };
  "@radix-ui/react-use-size@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-use-size/-/react-use-size-1.1.1.tgz";
    hash = "sha512-ewrXRDTAqAXlkl6t/fkXWNAhFX9I+CkKlw6zjEwk86RSPKwZr3xpBRso655aqYafwtnbpHLj6toFzmd6xdVptQ==";
  };
  "@radix-ui/react-visually-hidden@1.2.3" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/react-visually-hidden/-/react-visually-hidden-1.2.3.tgz";
    hash = "sha512-pzJq12tEaaIhqjbzpCuv/OypJY/BPavOofm+dbab+MHLajy277+1lLm6JFcGgF5eskJ6mquGirhXY2GD/8u8Ug==";
  };
  "@radix-ui/rect@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@radix-ui/rect/-/rect-1.1.1.tgz";
    hash = "sha512-HPwpGIzkl28mWyZqG52jiqDJ12waP11Pa1lGoiyUkIEuMLBP0oeK/C89esbXrxsky5we7dfd8U58nm0SgAWpVw==";
  };
  "@reduxjs/toolkit@2.8.2" = fetchurl {
    url = "https://registry.npmjs.org/@reduxjs/toolkit/-/toolkit-2.8.2.tgz";
    hash = "sha512-MYlOhQ0sLdw4ud48FoC5w0dH9VfWQjtCjreKwYTT3l+r427qYC5Y8PihNutepr8XrNaBUDQo9khWUwQxZaqt5A==";
  };
  "@standard-schema/spec@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.0.0.tgz";
    hash = "sha512-m2bOd0f2RT9k8QJx1JN85cZYyH1RqFBdlwtkSlf4tBDYLCiiZnv1fIIwacK6cqwXavOydf0NPToMQgpKq+dVlA==";
  };
  "@standard-schema/utils@0.3.0" = fetchurl {
    url = "https://registry.npmjs.org/@standard-schema/utils/-/utils-0.3.0.tgz";
    hash = "sha512-e7Mew686owMaPJVNNLs55PUvgz371nKgwsc4vxE49zsODpJEnxgxRo2y/OKrqueavXgZNMDVj3DdHFlaSAeU8g==";
  };
  "@tanstack/query-core@5.83.0" = fetchurl {
    url = "https://registry.npmjs.org/@tanstack/query-core/-/query-core-5.83.0.tgz";
    hash = "sha512-0M8dA+amXUkyz5cVUm/B+zSk3xkQAcuXuz5/Q/LveT4ots2rBpPTZOzd7yJa2Utsf8D2Upl5KyjhHRY+9lB/XA==";
  };
  "@tanstack/react-query@5.83.0" = fetchurl {
    url = "https://registry.npmjs.org/@tanstack/react-query/-/react-query-5.83.0.tgz";
    hash = "sha512-/XGYhZ3foc5H0VM2jLSD/NyBRIOK4q9kfeml4+0x2DlL6xVuAcVEW+hTlTapAmejObg0i3eNqhkr2dT+eciwoQ==";
  };
  "@types/bun@1.1.15" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.1.15.tgz";
    hash = "sha512-Fi7ND1jCq8O5iU3s9z3TKHggD0hidgpe7wSxyisviXpbMmY4B1KiokF3f/mmjOoDrEcf873tSpixgen7Wm9X0g==";
  };
  "@types/bun@1.2.19" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.2.19.tgz";
    hash = "sha512-d9ZCmrH3CJ2uYKXQIUuZ/pUnTqIvLDS0SK7pFmbx8ma+ziH/FRMoAq5bYpRG7y+w1gl+HgyNZbtqgMq4W4e2Lg==";
  };
  "@types/bun@1.2.20" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.2.20.tgz";
    hash = "sha512-dX3RGzQ8+KgmMw7CsW4xT5ITBSCrSbfHc36SNT31EOUg/LA9JWq0VDdEXDRSe1InVWpd2yLUM1FUF/kEOyTzYA==";
  };
  "@types/d3-array@3.2.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-array/-/d3-array-3.2.1.tgz";
    hash = "sha512-Y2Jn2idRrLzUfAKV2LyRImR+y4oa2AntrgID95SHJxuMUrkNXmanDSed71sRNZysveJVt1hLLemQZIady0FpEg==";
  };
  "@types/d3-color@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-color/-/d3-color-3.1.3.tgz";
    hash = "sha512-iO90scth9WAbmgv7ogoq57O9YpKmFBbmoEoCHDB2xMBY0+/KVrqAaCDyCE16dUspeOvIxFFRI+0sEtqDqy2b4A==";
  };
  "@types/d3-ease@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-ease/-/d3-ease-3.0.2.tgz";
    hash = "sha512-NcV1JjO5oDzoK26oMzbILE6HW7uVXOHLQvHshBUW4UMdZGfiY6v5BeQwh9a9tCzv+CeefZQHJt5SRgK154RtiA==";
  };
  "@types/d3-interpolate@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-interpolate/-/d3-interpolate-3.0.4.tgz";
    hash = "sha512-mgLPETlrpVV1YRJIglr4Ez47g7Yxjl1lj7YKsiMCb27VJH9W8NVM6Bb9d8kkpG/uAQS5AmbA48q2IAolKKo1MA==";
  };
  "@types/d3-path@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-path/-/d3-path-3.1.1.tgz";
    hash = "sha512-VMZBYyQvbGmWyWVea0EHs/BwLgxc+MKi1zLDCONksozI4YJMcTt8ZEuIR4Sb1MMTE8MMW49v0IwI5+b7RmfWlg==";
  };
  "@types/d3-scale@4.0.9" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-scale/-/d3-scale-4.0.9.tgz";
    hash = "sha512-dLmtwB8zkAeO/juAMfnV+sItKjlsw2lKdZVVy6LRr0cBmegxSABiLEpGVmSJJ8O08i4+sGR6qQtb6WtuwJdvVw==";
  };
  "@types/d3-shape@3.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-shape/-/d3-shape-3.1.7.tgz";
    hash = "sha512-VLvUQ33C+3J+8p+Daf+nYSOsjB4GXp19/S/aGo60m9h1v6XaxjiT82lKVWJCfzhtuZ3yD7i/TPeC/fuKLLOSmg==";
  };
  "@types/d3-time@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-time/-/d3-time-3.0.4.tgz";
    hash = "sha512-yuzZug1nkAAaBlBBikKZTgzCeA+k1uy4ZFwWANOfKw5z5LRhV0gNA7gNkKm7HoK+HRN0wX3EkxGk0fpbWhmB7g==";
  };
  "@types/d3-timer@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@types/d3-timer/-/d3-timer-3.0.2.tgz";
    hash = "sha512-Ps3T8E8dZDam6fUyNiMkekK3XUsaUEik+idO9/YjPtfj2qruF8tFBXS7XhtE4iIXBLxhmLjP3SXpLhVf21I9Lw==";
  };
  "@types/history@4.7.11" = fetchurl {
    url = "https://registry.npmjs.org/@types/history/-/history-4.7.11.tgz";
    hash = "sha512-qjDJRrmvBMiTx+jyLxvLfJU7UznFuokDv4f3WRuriHKERccVpFU+8XMQUAbDzoiJCsmexxRExQeMwwCdamSKDA==";
  };
  "@types/node@20.12.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-20.12.14.tgz";
    hash = "sha512-scnD59RpYD91xngrQQLGkE+6UrHUPzeKZWhhjBSa3HSkwjbQc38+q3RoIVEwxQGRw3M+j5hpNAM+lgV3cVormg==";
  };
  "@types/node@20.19.9" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-20.19.9.tgz";
    hash = "sha512-cuVNgarYWZqxRJDQHEB58GEONhOK79QVR/qYx4S7kcUObQvUwvFnYxJuuHUKm2aieN9X3yZB4LZsuYNU1Qphsw==";
  };
  "@types/node@22.17.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-22.17.0.tgz";
    hash = "sha512-bbAKTCqX5aNVryi7qXVMi+OkB3w/OyblodicMbvE38blyAz7GxXf6XYhklokijuPwwVg9sDLKRxt0ZHXQwZVfQ==";
  };
  "@types/react-dom@19.1.7" = fetchurl {
    url = "https://registry.npmjs.org/@types/react-dom/-/react-dom-19.1.7.tgz";
    hash = "sha512-i5ZzwYpqjmrKenzkoLM2Ibzt6mAsM7pxB6BCIouEVVmgiqaMj1TjaK7hnA36hbW5aZv20kx7Lw6hWzPWg0Rurw==";
  };
  "@types/react-router-dom@5.3.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/react-router-dom/-/react-router-dom-5.3.3.tgz";
    hash = "sha512-kpqnYK4wcdm5UaWI3fLcELopqLrHgLqNsdpHauzlQktfkHL3npOSwtj1Uz9oKBAzs7lFtVkV8j83voAz2D8fhw==";
  };
  "@types/react-router@5.1.20" = fetchurl {
    url = "https://registry.npmjs.org/@types/react-router/-/react-router-5.1.20.tgz";
    hash = "sha512-jGjmu/ZqS7FjSH6owMcD5qpq19+1RS9DeVRqfl1FeBMxTDQAGwlMWOcs52NDoXaNKyG3d1cYQFMs9rCrb88o9Q==";
  };
  "@types/react@19.1.9" = fetchurl {
    url = "https://registry.npmjs.org/@types/react/-/react-19.1.9.tgz";
    hash = "sha512-WmdoynAX8Stew/36uTSVMcLJJ1KRh6L3IZRx1PZ7qJtBqT3dYTgyDTx8H1qoRghErydW7xw9mSJ3wS//tCRpFA==";
  };
  "@types/use-sync-external-store@0.0.6" = fetchurl {
    url = "https://registry.npmjs.org/@types/use-sync-external-store/-/use-sync-external-store-0.0.6.tgz";
    hash = "sha512-zFDAD+tlpf2r4asuHEj0XH6pY6i0g5NeAHPn+15wk3BV6JA69eERFXC1gyGThDkVa1zCyKr5jox1+2LbV/AMLg==";
  };
  "@types/ws@8.5.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/ws/-/ws-8.5.14.tgz";
    hash = "sha512-bd/YFLW+URhBzMXurx7lWByOu+xzU9+kb3RboOteXYDfW+tr+JZa99OyNmPINEGB/ahzKrEuc8rcv4gnpJmxTw==";
  };
  "ansi-escapes@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-7.0.0.tgz";
    hash = "sha512-GdYO7a61mR0fOlAsvC9/rIHf7L96sBc6dEWzeOu+KAea5bZyQRPIpojrVoI4AXGJS/ycu/fBTdLrUkA4ODrvjw==";
  };
  "ansi-regex@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.1.0.tgz";
    hash = "sha512-7HSX4QQb4CspciLpVFwyRe79O3xsIZDDLER21kERQ71oaPodF8jL725AgJMFAYbooIqolJoRLuM81SpeUkpkvA==";
  };
  "ansi-styles@6.2.1" = fetchurl {
    url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
    hash = "sha512-bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
  };
  "aria-hidden@1.2.6" = fetchurl {
    url = "https://registry.npmjs.org/aria-hidden/-/aria-hidden-1.2.6.tgz";
    hash = "sha512-ik3ZgC9dY/lYVVM++OISsaYDeg1tb0VtP5uL3ouh1koGOaUMDPpbFIei4JkFimWUFPn90sbMNMXQAIVOlnYKJA==";
  };
  "auto-bind@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/auto-bind/-/auto-bind-5.0.1.tgz";
    hash = "sha512-ooviqdwwgfIfNmDwo94wlshcdzfO64XV0Cg6oDsDYBJfITDz1EngD2z7DkbvCWn+XIMsIqW27sEVF6qcpJrRcg==";
  };
  "bun-plugin-tailwind@0.0.15" = fetchurl {
    url = "https://registry.npmjs.org/bun-plugin-tailwind/-/bun-plugin-tailwind-0.0.15.tgz";
    hash = "sha512-qtAXMNGG4R0UGGI8zWrqm2B7BdXqx48vunJXBPzfDOHPA5WkRUZdTSbE7TFwO4jLhYqSE23YMWsM9NhE6ovobw==";
  };
  "bun-types@1.1.42" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.1.42.tgz";
    hash = "sha512-beMbnFqWbbBQHll/bn3phSwmoOQmnX2nt8NI9iOQKFbgR5Z6rlH3YuaMdlid8vp5XGct3/W4QVQBmhoOEoe4nw==";
  };
  "bun-types@1.2.19" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.19.tgz";
    hash = "sha512-uAOTaZSPuYsWIXRpj7o56Let0g/wjihKCkeRqUBhlLVM/Bt+Fj9xTo+LhC1OV1XDaGkz4hNC80et5xgy+9KTHQ==";
  };
  "bun-types@1.2.20" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.20.tgz";
    hash = "sha512-pxTnQYOrKvdOwyiyd/7sMt9yFOenN004Y6O4lCcCUoKVej48FS5cvTw9geRaEcB9TsDZaJKAxPTVvi8tFsVuXA==";
  };
  "bundle-name@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/bundle-name/-/bundle-name-4.1.0.tgz";
    hash = "sha512-tjwM5exMg6BGRI+kNmTntNsvdZS1X8BFYS6tnJ2hdH0kVxM6/eVZ2xy+FqStSWvYmtfFMDLIxurorHwDKfDz5Q==";
  };
  "ccflare" = copyPathToStore ./apps/tui;
  "chalk@5.4.1" = fetchurl {
    url = "https://registry.npmjs.org/chalk/-/chalk-5.4.1.tgz";
    hash = "sha512-zgVZuo2WcZgfUEmsn6eO3kINexW8RAE4maiQ8QNs8CtpPCSyMiYsULR3HQYkm3w8FIA3SberyMJMSldGsW+U3w==";
  };
  "class-variance-authority@0.7.1" = fetchurl {
    url = "https://registry.npmjs.org/class-variance-authority/-/class-variance-authority-0.7.1.tgz";
    hash = "sha512-Ka+9Trutv7G8M6WT6SeiRWz792K5qEqIGEGzXKhAE6xOWAY6pPH8U+9IY3oCMv6kqTmLsv7Xh/2w2RigkePMsg==";
  };
  "cli-boxes@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-3.0.0.tgz";
    hash = "sha512-/lzGpEWL/8PfI0BmBOPRwp0c/wFNX1RdUML3jK/RcSBA9T8mZDdQpqYBKtCFTOfQbwPqWEOpjqW+Fnayc0969g==";
  };
  "cli-cursor@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-4.0.0.tgz";
    hash = "sha512-VGtlMu3x/4DOtIUwEkRezxUZ2lBacNJCHash0N0WeZDBS+7Ux1dm3XWAgWYxLJFMMdOeXMHXorshEFhbMSGelg==";
  };
  "cli-spinners@2.9.2" = fetchurl {
    url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-2.9.2.tgz";
    hash = "sha512-ywqV+5MmyL4E7ybXgKys4DugZbX0FC6LnwrhjuykIjnK9k8OQacQ7axGKnjDXWNhns0xot3bZI5h55H8yo9cJg==";
  };
  "cli-truncate@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/cli-truncate/-/cli-truncate-4.0.0.tgz";
    hash = "sha512-nPdaFdQ0h/GEigbPClz11D0v/ZJEwxmeVZGeMo3Z5StPtUTkA9o1lD6QwoirYiSDzbcwn2XcjwmCp68W1IS4TA==";
  };
  "clsx@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/clsx/-/clsx-2.1.1.tgz";
    hash = "sha512-eYm0QWBtUrBWZWG0d386OGAw16Z995PiOVo2B7bjWSbHedGl5e0ZWaq65kOGgUSNesEIDkB9ISbTg/JK9dhCZA==";
  };
  "cmdk@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/cmdk/-/cmdk-1.1.1.tgz";
    hash = "sha512-Vsv7kFaXm+ptHDMZ7izaRsP70GgrW9NBNGswt9OZaVBLlE0SNpDq8eu/VGXyF9r7M0azK3Wy7OlYXsuyYLFzHg==";
  };
  "code-excerpt@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/code-excerpt/-/code-excerpt-4.0.0.tgz";
    hash = "sha512-xxodCmBen3iy2i0WtAK8FlFNrRzjUqjRsMfho58xT/wvZU1YTM3fCnRjcy1gJPMepaRlgm/0e6w8SpWHpn3/cA==";
  };
  "convert-to-spaces@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/convert-to-spaces/-/convert-to-spaces-2.0.1.tgz";
    hash = "sha512-rcQ1bsQO9799wq24uE5AM2tAILy4gXGIK/njFWcVQkGNZ96edlpY+A7bjwvzjYvLDyzmG1MmMLZhpcsb+klNMQ==";
  };
  "cookie@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/cookie/-/cookie-1.0.2.tgz";
    hash = "sha512-9Kr/j4O16ISv8zBBhJoi4bXOYNTkFLOqSL3UDB0njXxCXNezjeyVrJyGOWtgfs/q2km1gwBcfH8q1yEGoMYunA==";
  };
  "csstype@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/csstype/-/csstype-3.1.3.tgz";
    hash = "sha512-M1uQkMl8rQK/szD0LNhtqxIPLpimGm8sOBwU7lLnCpSbTyY3yeU1Vc7l4KT5zT4s/yOxHH5O7tIuuLOCnLADRw==";
  };
  "d3-array@3.2.4" = fetchurl {
    url = "https://registry.npmjs.org/d3-array/-/d3-array-3.2.4.tgz";
    hash = "sha512-tdQAmyA18i4J7wprpYq8ClcxZy3SC31QMeByyCFyRt7BVHdREQZ5lpzoe5mFEYZUWe+oq8HBvk9JjpibyEV4Jg==";
  };
  "d3-color@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/d3-color/-/d3-color-3.1.0.tgz";
    hash = "sha512-zg/chbXyeBtMQ1LbD/WSoW2DpC3I0mpmPdW+ynRTj/x2DAWYrIY7qeZIHidozwV24m4iavr15lNwIwLxRmOxhA==";
  };
  "d3-ease@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/d3-ease/-/d3-ease-3.0.1.tgz";
    hash = "sha512-wR/XK3D3XcLIZwpbvQwQ5fK+8Ykds1ip7A2Txe0yxncXSdq1L9skcG7blcedkOX+ZcgxGAmLX1FrRGbADwzi0w==";
  };
  "d3-format@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/d3-format/-/d3-format-3.1.0.tgz";
    hash = "sha512-YyUI6AEuY/Wpt8KWLgZHsIU86atmikuoOmCfommt0LYHiQSPjvX2AcFc38PX0CBpr2RCyZhjex+NS/LPOv6YqA==";
  };
  "d3-interpolate@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-3.0.1.tgz";
    hash = "sha512-3bYs1rOD33uo8aqJfKP3JWPAibgw8Zm2+L9vBKEHJ2Rg+viTR7o5Mmv5mZcieN+FRYaAOWX5SJATX6k1PWz72g==";
  };
  "d3-path@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/d3-path/-/d3-path-3.1.0.tgz";
    hash = "sha512-p3KP5HCf/bvjBSSKuXid6Zqijx7wIfNW+J/maPs+iwR35at5JCbLUT0LzF1cnjbCHWhqzQTIN2Jpe8pRebIEFQ==";
  };
  "d3-scale@4.0.2" = fetchurl {
    url = "https://registry.npmjs.org/d3-scale/-/d3-scale-4.0.2.tgz";
    hash = "sha512-GZW464g1SH7ag3Y7hXjf8RoUuAFIqklOAq3MRl4OaWabTFJY9PN/E1YklhXLh+OQ3fM9yS2nOkCoS+WLZ6kvxQ==";
  };
  "d3-shape@3.2.0" = fetchurl {
    url = "https://registry.npmjs.org/d3-shape/-/d3-shape-3.2.0.tgz";
    hash = "sha512-SaLBuwGm3MOViRq2ABk3eLoxwZELpH6zhl3FbAoJ7Vm1gofKx6El1Ib5z23NUEhF9AsGl7y+dzLe5Cw2AArGTA==";
  };
  "d3-time-format@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-4.1.0.tgz";
    hash = "sha512-dJxPBlzC7NugB2PDLwo9Q8JiTR3M3e4/XANkreKSUxF8vvXKqm1Yfq4Q5dl8budlunRVlUUaDUgFt7eA8D6NLg==";
  };
  "d3-time@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/d3-time/-/d3-time-3.1.0.tgz";
    hash = "sha512-VqKjzBLejbSMT4IgbmVgDjpkYrNWUYJnbCGo874u7MMKIWsILRX+OpX/gTk8MqjpT1A/c6HY2dCA77ZN0lkQ2Q==";
  };
  "d3-timer@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/d3-timer/-/d3-timer-3.0.1.tgz";
    hash = "sha512-ndfJ/JxxMd3nw31uyKoY2naivF+r29V+Lc0svZxe1JvvIRmi8hUsrMvdOwgS1o6uBHmiz91geQ0ylPP0aj1VUA==";
  };
  "date-fns@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/date-fns/-/date-fns-4.1.0.tgz";
    hash = "sha512-Ukq0owbQXxa/U3EGtsdVBkR1w7KOQ5gIBqdH2hkvknzZPYvBxb/aa6E8L7tmjFtkwZBu3UXBbjIgPo/Ez4xaNg==";
  };
  "decimal.js-light@2.5.1" = fetchurl {
    url = "https://registry.npmjs.org/decimal.js-light/-/decimal.js-light-2.5.1.tgz";
    hash = "sha512-qIMFpTMZmny+MMIitAB6D7iVPEorVw6YQRWkvarTkT4tBeSLLiHzcwj6q0MmYSFCiVpiqPJTJEYIrpcPzVEIvg==";
  };
  "default-browser-id@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/default-browser-id/-/default-browser-id-5.0.0.tgz";
    hash = "sha512-A6p/pu/6fyBcA1TRz/GqWYPViplrftcW2gZC9q79ngNCKAeR/X3gcEdXQHl4KNXV+3wgIJ1CPkJQ3IHM6lcsyA==";
  };
  "default-browser@5.2.1" = fetchurl {
    url = "https://registry.npmjs.org/default-browser/-/default-browser-5.2.1.tgz";
    hash = "sha512-WY/3TUME0x3KPYdRRxEJJvXRHV4PyPoUsxtZa78lwItwRQRHhd2U9xOscaT/YTf8uCXIAjeJOFBVEh/7FtD8Xg==";
  };
  "define-lazy-prop@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-3.0.0.tgz";
    hash = "sha512-N+MeXYoqr3pOgn8xfyRPREN7gHakLYjhsHhWGT3fWAiL4IkAt0iDw14QiiEm2bE30c5XX5q0FtAA3CK5f9/BUg==";
  };
  "detect-node-es@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/detect-node-es/-/detect-node-es-1.1.0.tgz";
    hash = "sha512-ypdmJU/TbBby2Dxibuv7ZLW3Bs1QEmM7nHjEANfohJLvE0XVujisn1qPJcZxg+qDucsr+bP6fLD1rPS3AhJ7EQ==";
  };
  "emoji-regex@10.4.0" = fetchurl {
    url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.4.0.tgz";
    hash = "sha512-EC+0oUMY1Rqm4O6LLrgjtYDvcVYTy7chDnM4Q7030tP4Kwj3u/pR6gP9ygnp2CJMK5Gq+9Q2oqmrFJAz01DXjw==";
  };
  "environment@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/environment/-/environment-1.1.0.tgz";
    hash = "sha512-xUtoPkMggbz0MPyPiIWr1Kp4aeWJjDZ6SMvURhimjdZgsRuDplF5/s9hcgGhyXMhs+6vpnuoiZ2kFiu3FMnS8Q==";
  };
  "es-toolkit@1.39.8" = fetchurl {
    url = "https://registry.npmjs.org/es-toolkit/-/es-toolkit-1.39.8.tgz";
    hash = "sha512-A8QO9TfF+rltS8BXpdu8OS+rpGgEdnRhqIVxO/ZmNvnXBYgOdSsxukT55ELyP94gZIntWJ+Li9QRrT2u1Kitpg==";
  };
  "escape-string-regexp@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
    hash = "sha512-UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
  };
  "eventemitter3@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-5.0.1.tgz";
    hash = "sha512-GWkBvjiSZK87ELrYOSESUYeVIc9mvLLf/nXalMOS5dYrgZq9o5OVkbZAVM06CVxYsCwH9BDZFPlQTlPA1j4ahA==";
  };
  "figures@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/figures/-/figures-6.1.0.tgz";
    hash = "sha512-d+l3qxjSesT4V7v2fh+QnmFnUWv9lSpjarhShNTgBOfA0ttejbQUAlHLitbjkoRiDulW0OPoQPYIGhIC8ohejg==";
  };
  "framer-motion@12.23.11" = fetchurl {
    url = "https://registry.npmjs.org/framer-motion/-/framer-motion-12.23.11.tgz";
    hash = "sha512-VzNi+exyI3bn7Pzvz1Fjap1VO9gQu8mxrsSsNamMidsZ8AA8W2kQsR+YQOciEUbMtkKAWIbPHPttfn5e9jqqJQ==";
  };
  "get-east-asian-width@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.3.0.tgz";
    hash = "sha512-vpeMIQKxczTD/0s2CdEWHcb0eeJe6TFjxb+J5xgX7hScxqrGuyjmv4c1D4A/gelKfyox0gJJwIHF+fLjeaM8kQ==";
  };
  "get-nonce@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/get-nonce/-/get-nonce-1.0.1.tgz";
    hash = "sha512-FJhYRoDaiatfEkUK8HKlicmu/3SGFD51q3itKDGoSTysQJBnfOcxU5GxnhE1E6soB76MbT0MBtnKJuXyAx+96Q==";
  };
  "immer@10.1.1" = fetchurl {
    url = "https://registry.npmjs.org/immer/-/immer-10.1.1.tgz";
    hash = "sha512-s2MPrmjovJcoMaHtx6K11Ra7oD05NT97w1IC5zpMkT6Atjr7H8LjaDd81iIxUYpMKSRRNMJE703M1Fhr/TctHw==";
  };
  "indent-string@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/indent-string/-/indent-string-5.0.0.tgz";
    hash = "sha512-m6FAo/spmsW2Ab2fU35JTYwtOKa2yAwXSwgjSv1TJzh4Mh7mC3lzAOVLBprb72XsTrgkEIsl7YrFNAiDiRhIGg==";
  };
  "ink-select-input@6.2.0" = fetchurl {
    url = "https://registry.npmjs.org/ink-select-input/-/ink-select-input-6.2.0.tgz";
    hash = "sha512-304fZXxkpYxJ9si5lxRCaX01GNlmPBgOZumXXRnPYbHW/iI31cgQynqk2tRypGLOF1cMIwPUzL2LSm6q4I5rQQ==";
  };
  "ink-spinner@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/ink-spinner/-/ink-spinner-5.0.0.tgz";
    hash = "sha512-EYEasbEjkqLGyPOUc8hBJZNuC5GvXGMLu0w5gdTNskPc7Izc5vO3tdQEYnzvshucyGCBXc86ig0ujXPMWaQCdA==";
  };
  "ink-text-input@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/ink-text-input/-/ink-text-input-6.0.0.tgz";
    hash = "sha512-Fw64n7Yha5deb1rHY137zHTAbSTNelUKuB5Kkk2HACXEtwIHBCf9OH2tP/LQ9fRYTl1F0dZgbW0zPnZk6FA9Lw==";
  };
  "ink@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/ink/-/ink-6.1.0.tgz";
    hash = "sha512-YQ+lbMD79y3FBAJXXZnuRajLEgaMFp102361eY5NrBIEVCi9oFo7gNZU4z2LBWlcjZFiTt7jetlkIbKCCH4KJA==";
  };
  "internmap@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/internmap/-/internmap-2.0.3.tgz";
    hash = "sha512-5Hh7Y1wQbvY5ooGgPbDaL5iYLAPzMTUrjMulskHLH6wnv/A+1q5rgEaiuqEjB+oxGXIVZs1FF+R/KPN3ZSQYYg==";
  };
  "is-docker@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
    hash = "sha512-eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
  };
  "is-fullwidth-code-point@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-4.0.0.tgz";
    hash = "sha512-O4L094N2/dZ7xqVdrXhh9r1KODPJpFms8B5sGdJLPy664AgvXsreZUyCQQNItZRDlYug4xStLjNp/sz3HvBowQ==";
  };
  "is-fullwidth-code-point@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-5.0.0.tgz";
    hash = "sha512-OVa3u9kkBbw7b8Xw5F9P+D/T9X+Z4+JruYVNapTjPYZYUznQ5YfWeFkOj606XYYW8yugTfC8Pj0hYqvi4ryAhA==";
  };
  "is-in-ci@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-in-ci/-/is-in-ci-1.0.0.tgz";
    hash = "sha512-eUuAjybVTHMYWm/U+vBO1sY/JOCgoPCXRxzdju0K+K0BiGW0SChEL1MLC0PoCIR1OlPo5YAp8HuQoUlsWEICwg==";
  };
  "is-inside-container@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
    hash = "sha512-KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
  };
  "is-unicode-supported@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-2.1.0.tgz";
    hash = "sha512-mE00Gnza5EEB3Ds0HfMyllZzbBrmLOX3vfWoj9A9PEnTfratQ/BcaJOuMhnkhjXvb2+FkY3VuHqtAGpTPmglFQ==";
  };
  "is-wsl@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.0.tgz";
    hash = "sha512-UcVfVfaK4Sc4m7X3dUSoHoozQGBEFeDC+zVo06t98xe8CzHSZZBekNXH+tu0NalHolcJ/QAGqS46Hef7QXBIMw==";
  };
  "js-tokens@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
    hash = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
  };
  "loose-envify@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
    hash = "sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
  };
  "lucide-react@0.525.0" = fetchurl {
    url = "https://registry.npmjs.org/lucide-react/-/lucide-react-0.525.0.tgz";
    hash = "sha512-Tm1txJ2OkymCGkvwoHt33Y2JpN5xucVq1slHcgE6Lk0WjDfjgKWor5CdVER8U6DvcfMwh4M8XxmpTiyzfmfDYQ==";
  };
  "mimic-fn@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
    hash = "sha512-OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
  };
  "motion-dom@12.23.9" = fetchurl {
    url = "https://registry.npmjs.org/motion-dom/-/motion-dom-12.23.9.tgz";
    hash = "sha512-6Sv++iWS8XMFCgU1qwKj9l4xuC47Hp4+2jvPfyTXkqDg2tTzSgX6nWKD4kNFXk0k7llO59LZTPuJigza4A2K1A==";
  };
  "motion-utils@12.23.6" = fetchurl {
    url = "https://registry.npmjs.org/motion-utils/-/motion-utils-12.23.6.tgz";
    hash = "sha512-eAWoPgr4eFEOFfg2WjIsMoqJTW6Z8MTUCgn/GZ3VRpClWBdnbjryiA3ZSNLyxCTmCQx4RmYX6jX1iWHbenUPNQ==";
  };
  "onetime@5.1.2" = fetchurl {
    url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
    hash = "sha512-kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
  };
  "open@10.2.0" = fetchurl {
    url = "https://registry.npmjs.org/open/-/open-10.2.0.tgz";
    hash = "sha512-YgBpdJHPyQ2UE5x+hlSXcnejzAvD0b22U2OuAP+8OnlJT+PjWPxtgmGqKKc+RgTM63U9gN0YzrYc71R2WT/hTA==";
  };
  "patch-console@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/patch-console/-/patch-console-2.0.0.tgz";
    hash = "sha512-0YNdUceMdaQwoKce1gatDScmMo5pu/tfABfnzEqeG0gtTmd7mh/WcwgUjtAeOU7N8nFFlbQBnFK2gXW5fGvmMA==";
  };
  "react-devtools-core@5.3.2" = fetchurl {
    url = "https://registry.npmjs.org/react-devtools-core/-/react-devtools-core-5.3.2.tgz";
    hash = "sha512-crr9HkVrDiJ0A4zot89oS0Cgv0Oa4OG1Em4jit3P3ZxZSKPMYyMjfwMqgcJna9o625g8oN87rBm8SWWrSTBZxg==";
  };
  "react-dom@19.1.1" = fetchurl {
    url = "https://registry.npmjs.org/react-dom/-/react-dom-19.1.1.tgz";
    hash = "sha512-Dlq/5LAZgF0Gaz6yiqZCf6VCcZs1ghAJyrsu84Q/GT0gV+mCxbfmKNoGRKBYMJ8IEdGPqu49YWXD02GCknEDkw==";
  };
  "react-is@19.1.1" = fetchurl {
    url = "https://registry.npmjs.org/react-is/-/react-is-19.1.1.tgz";
    hash = "sha512-tr41fA15Vn8p4X9ntI+yCyeGSf1TlYaY5vlTZfQmeLBrFo3psOPX6HhTDnFNL9uj3EhP0KAQ80cugCl4b4BERA==";
  };
  "react-reconciler@0.32.0" = fetchurl {
    url = "https://registry.npmjs.org/react-reconciler/-/react-reconciler-0.32.0.tgz";
    hash = "sha512-2NPMOzgTlG0ZWdIf3qG+dcbLSoAc/uLfOwckc3ofy5sSK0pLJqnQLpUFxvGcN2rlXSjnVtGeeFLNimCQEj5gOQ==";
  };
  "react-redux@9.2.0" = fetchurl {
    url = "https://registry.npmjs.org/react-redux/-/react-redux-9.2.0.tgz";
    hash = "sha512-ROY9fvHhwOD9ySfrF0wmvu//bKCQ6AeZZq1nJNtbDC+kk5DuSuNX/n6YWYF/SYy7bSba4D4FSz8DJeKY/S/r+g==";
  };
  "react-remove-scroll-bar@2.3.8" = fetchurl {
    url = "https://registry.npmjs.org/react-remove-scroll-bar/-/react-remove-scroll-bar-2.3.8.tgz";
    hash = "sha512-9r+yi9+mgU33AKcj6IbT9oRCO78WriSj6t/cF8DWBZJ9aOGPOTEDvdUDz1FwKim7QXWwmHqtdHnRJfhAxEG46Q==";
  };
  "react-remove-scroll@2.7.1" = fetchurl {
    url = "https://registry.npmjs.org/react-remove-scroll/-/react-remove-scroll-2.7.1.tgz";
    hash = "sha512-HpMh8+oahmIdOuS5aFKKY6Pyog+FNaZV/XyJOq7b4YFwsFHe5yYfdbIalI4k3vU2nSDql7YskmUseHsRrJqIPA==";
  };
  "react-router-dom@7.8.1" = fetchurl {
    url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-7.8.1.tgz";
    hash = "sha512-NkgBCF3sVgCiAWIlSt89GR2PLaksMpoo3HDCorpRfnCEfdtRPLiuTf+CNXvqZMI5SJLZCLpVCvcZrTdtGW64xQ==";
  };
  "react-router@7.8.1" = fetchurl {
    url = "https://registry.npmjs.org/react-router/-/react-router-7.8.1.tgz";
    hash = "sha512-5cy/M8DHcG51/KUIka1nfZ2QeylS4PJRs6TT8I4PF5axVsI5JUxp0hC0NZ/AEEj8Vw7xsEoD7L/6FY+zoYaOGA==";
  };
  "react-style-singleton@2.2.3" = fetchurl {
    url = "https://registry.npmjs.org/react-style-singleton/-/react-style-singleton-2.2.3.tgz";
    hash = "sha512-b6jSvxvVnyptAiLjbkWLE/lOnR4lfTtDAl+eUC7RZy+QQWc6wRzIV2CE6xBuMmDxc2qIihtDCZD5NPOFl7fRBQ==";
  };
  "react@19.1.1" = fetchurl {
    url = "https://registry.npmjs.org/react/-/react-19.1.1.tgz";
    hash = "sha512-w8nqGImo45dmMIfljjMwOGtbmC/mk4CMYhWIicdSflH91J9TyCyczcPFXJzrZ/ZXcgGRFeP6BU0BEJTw6tZdfQ==";
  };
  "recharts@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/recharts/-/recharts-3.1.0.tgz";
    hash = "sha512-NqAqQcGBmLrfDs2mHX/bz8jJCQtG2FeXfE0GqpZmIuXIjkpIwj8sd9ad0WyvKiBKPd8ZgNG0hL85c8sFDwascw==";
  };
  "redux-thunk@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/redux-thunk/-/redux-thunk-3.1.0.tgz";
    hash = "sha512-NW2r5T6ksUKXCabzhL9z+h206HQw/NJkcLm1GPImRQ8IzfXwRGqjVhKJGauHirT0DAuyy6hjdnMZaRoAcy0Klw==";
  };
  "redux@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/redux/-/redux-5.0.1.tgz";
    hash = "sha512-M9/ELqF6fy8FwmkpnF0S3YKOqMyoWJ4+CS5Efg2ct3oY9daQvd/Pc71FpGZsVsbl3Cpb+IIcjBDUnnyBdQbq4w==";
  };
  "reselect@5.1.1" = fetchurl {
    url = "https://registry.npmjs.org/reselect/-/reselect-5.1.1.tgz";
    hash = "sha512-K/BG6eIky/SBpzfHZv/dd+9JBFiS4SWV7FIujVyJRux6e45+73RaUHXLmIR1f7WOMaQ0U1km6qwklRQxpJJY0w==";
  };
  "restore-cursor@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-4.0.0.tgz";
    hash = "sha512-I9fPXU9geO9bHOt9pHHOhOkYerIMsmVaWB0rA2AI9ERh/+x/i7MV5HKBNrg+ljO5eoPVgCcnFuRjJ9uH6I/3eg==";
  };
  "run-applescript@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/run-applescript/-/run-applescript-7.0.0.tgz";
    hash = "sha512-9by4Ij99JUr/MCFBUkDKLWK3G9HVXmabKz9U5MlIAIuvuzkiOicRYs8XJLxX+xahD+mLiiCYDqF9dKAgtzKP1A==";
  };
  "scheduler@0.23.2" = fetchurl {
    url = "https://registry.npmjs.org/scheduler/-/scheduler-0.23.2.tgz";
    hash = "sha512-UOShsPwz7NrMUqhR6t0hWjFduvOzbtv7toDH1/hIrfRNIDBnnBWd0CwJTGvTpngVlmwGCdP9/Zl/tVrDqcuYzQ==";
  };
  "scheduler@0.26.0" = fetchurl {
    url = "https://registry.npmjs.org/scheduler/-/scheduler-0.26.0.tgz";
    hash = "sha512-NlHwttCI/l5gCPR3D1nNXtWABUmBwvZpEQiD4IXSbIDq8BzLIK/7Ir5gTFSGZDUu37K5cMNp0hFtzO38sC7gWA==";
  };
  "set-cookie-parser@2.7.1" = fetchurl {
    url = "https://registry.npmjs.org/set-cookie-parser/-/set-cookie-parser-2.7.1.tgz";
    hash = "sha512-IOc8uWeOZgnb3ptbCURJWNjWUPcO3ZnTTdzsurqERrP6nPyv+paC55vJM0LpOlT2ne+Ix+9+CRG1MNLlyZ4GjQ==";
  };
  "shell-quote@1.8.3" = fetchurl {
    url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.8.3.tgz";
    hash = "sha512-ObmnIF4hXNg1BqhnHmgbDETF8dLPCggZWBjkQfhZpbszZnYur5DUljTcCHii5LC3J5E0yeO/1LIMyH+UvHQgyw==";
  };
  "signal-exit@3.0.7" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
    hash = "sha512-wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
  };
  "slice-ansi@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-5.0.0.tgz";
    hash = "sha512-FC+lgizVPfie0kkhqUScwRu1O/lF6NOgJmlCgK+/LYxDCTk8sGelYaHDhFcDN+Sn3Cv+3VSa4Byeo+IMCzpMgQ==";
  };
  "slice-ansi@7.1.0" = fetchurl {
    url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-7.1.0.tgz";
    hash = "sha512-bSiSngZ/jWeX93BqeIAbImyTbEihizcwNjFoRUIY/T1wWQsfsm2Vw1agPKylXvQTU7iASGdHhyqRlqQzfz+Htg==";
  };
  "stack-utils@2.0.6" = fetchurl {
    url = "https://registry.npmjs.org/stack-utils/-/stack-utils-2.0.6.tgz";
    hash = "sha512-XlkWvfIm6RmsWtNJx+uqtKLS8eqFbxUg0ZzLXqY0caEy9l7hruX8IpiDnjsLavoBgqCCR71TqWO8MaXYheJ3RQ==";
  };
  "string-width@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
    hash = "sha512-tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
  };
  "strip-ansi@7.1.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
    hash = "sha512-iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
  };
  "tailwind-merge@2.6.0" = fetchurl {
    url = "https://registry.npmjs.org/tailwind-merge/-/tailwind-merge-2.6.0.tgz";
    hash = "sha512-P+Vu1qXfzediirmHOC3xKGAYeZtPcV9g76X+xg2FD4tYgR71ewMA35Y3sCz3zhiN/dwefRpJX0yBcgwi1fXNQA==";
  };
  "tailwindcss-animate@1.0.7" = fetchurl {
    url = "https://registry.npmjs.org/tailwindcss-animate/-/tailwindcss-animate-1.0.7.tgz";
    hash = "sha512-bl6mpH3T7I3UFxuvDEXLxy/VuFxBk5bbzplh7tXI68mwMokNYd1t9qPBHlnyTwfa4JGC4zP516I1hYYtQ/vspA==";
  };
  "tailwindcss@4.1.11" = fetchurl {
    url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.1.11.tgz";
    hash = "sha512-2E9TBm6MDD/xKYe+dvJZAmg3yxIEDNRc0jwlNyDg/4Fil2QcSLjFKGVff0lAf1jjeaArlG/M75Ey/EYr/OJtBA==";
  };
  "tiny-invariant@1.3.3" = fetchurl {
    url = "https://registry.npmjs.org/tiny-invariant/-/tiny-invariant-1.3.3.tgz";
    hash = "sha512-+FbBPE1o9QAYvviau/qC5SE3caw21q3xkvWKBtja5vgqOWIHHJ3ioaq1VPfn/Szqctz2bU/oYeKd9/z5BL+PVg==";
  };
  "to-rotated@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/to-rotated/-/to-rotated-1.0.0.tgz";
    hash = "sha512-KsEID8AfgUy+pxVRLsWp0VzCa69wxzUDZnzGbyIST/bcgcrMvTYoFBX/QORH4YApoD89EDuUovx4BTdpOn319Q==";
  };
  "tslib@2.8.1" = fetchurl {
    url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
    hash = "sha512-oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
  };
  "type-fest@4.41.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-4.41.0.tgz";
    hash = "sha512-TeTSQ6H5YHvpqVwBRcnLDCBnDOHWYu7IvGbHT6N8AOymcr9PJGjc1GTtiWZTYg0NCgYwvnYWEkVChQAr9bjfwA==";
  };
  "typescript@5.7.2" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.7.2.tgz";
    hash = "sha512-i5t66RHxDvVN40HfDd1PsEThGNnlMCMT3jMUuoh9/0TaqWevNontacunWyN02LA9/fIbEWlcHZcgTKb9QoaLfg==";
  };
  "typescript@5.8.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.8.3.tgz";
    hash = "sha512-p1diW6TqL9L07nNxvRMM7hMMw4c5XOo/1ibL4aAIGmSAt9slTE1Xgw5KWuof2uTOvCg9BY7ZRi+GaF+7sfgPeQ==";
  };
  "undici-types@5.26.5" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-5.26.5.tgz";
    hash = "sha512-JlCMO+ehdEIKqlFxk6IfVoAUVmgz7cU7zD/h9XZ0qzeosSHmUJVOzSQvvYSYWXkFXC+IfLKSIffhv0sVZup6pA==";
  };
  "undici-types@6.21.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-6.21.0.tgz";
    hash = "sha512-iwDZqg0QAGrg9Rav5H4n0M64c3mkR59cJ6wQp+7C4nI0gsmExaedaYLNO44eT4AtBBwjbTiGPMlt2Md0T9H9JQ==";
  };
  "use-callback-ref@1.3.3" = fetchurl {
    url = "https://registry.npmjs.org/use-callback-ref/-/use-callback-ref-1.3.3.tgz";
    hash = "sha512-jQL3lRnocaFtu3V00JToYz/4QkNWswxijDaCVNZRiRTO3HQDLsdu1ZtmIUvV4yPp+rvWm5j0y0TG/S61cuijTg==";
  };
  "use-sidecar@1.1.3" = fetchurl {
    url = "https://registry.npmjs.org/use-sidecar/-/use-sidecar-1.1.3.tgz";
    hash = "sha512-Fedw0aZvkhynoPYlA5WXrMCAMm+nSWdZt6lzJQ7Ok8S6Q+VsHmHpRWndVRJ8Be0ZbkfPc5LRYH+5XrzXcEeLRQ==";
  };
  "use-sync-external-store@1.5.0" = fetchurl {
    url = "https://registry.npmjs.org/use-sync-external-store/-/use-sync-external-store-1.5.0.tgz";
    hash = "sha512-Rb46I4cGGVBmjamjphe8L/UnvJD+uPPtTkNvX5mZgqdbavhI4EbgIWJiIHXJ8bc/i9EQGPRh4DwEURJ552Do0A==";
  };
  "victory-vendor@37.3.6" = fetchurl {
    url = "https://registry.npmjs.org/victory-vendor/-/victory-vendor-37.3.6.tgz";
    hash = "sha512-SbPDPdDBYp+5MJHhBCAyI7wKM3d5ivekigc2Dk2s7pgbZ9wIgIBYGVw4zGHBml/qTFbexrofXW6Gu4noGxrOwQ==";
  };
  "widest-line@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/widest-line/-/widest-line-5.0.0.tgz";
    hash = "sha512-c9bZp7b5YtRj2wOe6dlj32MK+Bx/M/d+9VB2SHM1OtsUHR0aV0tdP6DWh/iMt0kWi1t5g1Iudu6hQRNd1A4PVA==";
  };
  "wrap-ansi@9.0.0" = fetchurl {
    url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-9.0.0.tgz";
    hash = "sha512-G8ura3S+3Z2G+mkgNRq8dqaFZAuxfsxpBB8OCTGRTCtp+l/v9nbFNmCUP1BZMts3G1142MsZfn6eeUKrr4PD1Q==";
  };
  "ws@7.5.10" = fetchurl {
    url = "https://registry.npmjs.org/ws/-/ws-7.5.10.tgz";
    hash = "sha512-+dbF1tHwZpXcbOJdVOkzLDxZP1ailvSxM6ZweXTegylPny803bFhA+vqBYw4s31NSAk4S2Qz+AKXK9a4wkdjcQ==";
  };
  "ws@8.18.3" = fetchurl {
    url = "https://registry.npmjs.org/ws/-/ws-8.18.3.tgz";
    hash = "sha512-PEIGCY5tSlUt50cqyMXfCzX+oOPqN0vuGqWzbcJ2xvnkzkq46oOpz7dQaTDBdfICb4N14+GARUDw2XV2N4tvzg==";
  };
  "wsl-utils@0.1.0" = fetchurl {
    url = "https://registry.npmjs.org/wsl-utils/-/wsl-utils-0.1.0.tgz";
    hash = "sha512-h3Fbisa2nKGPxCpm89Hk33lBLsnaGBvctQopaBSOW/uIs6FTe1ATyAnKFJrzVs9vpGdsTe73WF3V4lIsk4Gacw==";
  };
  "yoga-layout@3.2.1" = fetchurl {
    url = "https://registry.npmjs.org/yoga-layout/-/yoga-layout-3.2.1.tgz";
    hash = "sha512-0LPOt3AxKqMdFBZA3HBAt/t/8vIKq7VaQYbuA8WxCgung+p9TVyKRYdpvCb80HcdTN2NkbIKbhNwKUfm3tQywQ==";
  };
}